#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-container
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_DATABASE: ecommerce
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  redis:
#    image: redis:7.0
#    container_name: redis-container
#    ports:
#      - "6379:6379"
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq-container
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#
#volumes:
#  mysql_data:
